version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: US/Eastern
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
